layout_spectrum: 0.5807717
color:
  saturation: 0.007668941
  lightness: 0.1675715
  brandStrength: 0.4221736
  brandColors:
    - '#1F171E'
    - '#E7D89A'
    - '#F30E1F'
    - '#999AB5'
    - '#F39B06'
  rhythmicContrast: 0.4927709
typography_spectrum: 0.3178375
name: 'Priyo Coolone '
